name: Hello workflow

on: push

jobs:
  hello-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job1
        run: echo "job1"
  hello-job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job2
        run: echo "job2"               